name: LAB Infrastructure Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_level:
        description: 'Test level to run'
        required: true
        default: 'quick'
        type: choice
        options:
        - quick
        - standard
        - comprehensive
        - full

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    name: Shell Script Syntax Check
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    
    - name: Run shellcheck on all scripts
      run: |
        find . -name "*.sh" -type f | xargs shellcheck -e SC1091,SC2034,SC2086,SC2162
    
    - name: Check script permissions
      run: |
        echo "Checking executable permissions..."
        ls -la *.sh
        test -x master_consolidated_test.sh
        test -x run_all_tests.sh
        test -x web_launcher.sh

  documentation-check:
    runs-on: ubuntu-latest
    name: Documentation Validation
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check README exists and has content
      run: |
        test -f README.md
        test -s README.md
        echo "README.md exists and has content"
    
    - name: Check documentation completeness
      run: |
        echo "Checking documentation files..."
        test -f CONSOLIDATED_TESTING_SUITE.md
        echo "All documentation files present"
    
    - name: Validate HTML dashboard
      run: |
        test -f infrastructure_testing_dashboard.html
        grep -q "InfamousLab Infrastructure Testing Dashboard" infrastructure_testing_dashboard.html
        echo "HTML dashboard is valid"

  basic-functionality:
    runs-on: ubuntu-latest
    name: Basic Functionality Test
    needs: [syntax-check, documentation-check]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test script help functions
      run: |
        ./master_consolidated_test.sh --help
        ./run_all_tests.sh --help
        echo "Help functions working"
    
    - name: Test script dry-run mode
      run: |
        ./master_consolidated_test.sh --dry-run quick
        ./run_all_tests.sh --dry-run quick
        echo "Dry-run mode working"
    
    - name: Validate script configuration
      run: |
        echo "Checking script configurations..."
        grep -q "AWS_REGION" master_consolidated_test.sh
        grep -q "TUNNEL_URL" master_consolidated_test.sh
        echo "Configuration variables found"

  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run basic security checks
      run: |
        echo "Checking for sensitive data in scripts..."
        ! grep -r "password\|secret\|key\|token" --include="*.sh" . || echo "No hardcoded secrets found"
        
    - name: Check file permissions
      run: |
        echo "Checking file permissions..."
        find . -name "*.sh" -perm /u+x,g+x,o+x
        echo "Executable permissions verified"

  notify-completion:
    runs-on: ubuntu-latest
    name: Notify Test Completion
    needs: [syntax-check, documentation-check, basic-functionality, security-scan]
    if: always()
    
    steps:
    - name: Test Summary
      run: |
        echo "🧪 LAB-Automated-Test CI/CD Pipeline Complete"
        echo "✅ Syntax Check: ${{ needs.syntax-check.result }}"
        echo "✅ Documentation: ${{ needs.documentation-check.result }}"
        echo "✅ Functionality: ${{ needs.basic-functionality.result }}"
        echo "✅ Security Scan: ${{ needs.security-scan.result }}"
        echo ""
        echo "Repository: https://github.com/${{ github.repository }}"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
